<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Canaa.DataContracts\Canaa.DataContracts.csproj" />
    <ProjectReference Include="..\Canaa.Infra.ExternalServices\Canaa.Infra.ExternalServices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utils\" />
    <Folder Include="Midia\Video\Temp\" />
    <Folder Include="WhatsApp\" />
  </ItemGroup>

</Project>
