<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Canaa\appsettings.json" Link="appsettings.json" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.13">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
		<PackageReference Include="Ninject.Web.Common" Version="3.3.2" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
		<PackageReference Include="MySql.Data" Version="9.2.0" />
		<PackageReference Include="Ninject" Version="3.3.6" />
		<PackageReference Include="Xabe.FFmpeg" Version="6.0.1" />
		<PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.1" />
		<PackageReference Include="YoutubeExplode" Version="6.5.4" />
		<PackageReference Include="YoutubeExplode.Converter" Version="6.5.4" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\Canaa.DataContracts\Canaa.DataContracts.csproj" />
    <ProjectReference Include="..\Canaa.Infra.Entities\Canaa.Infra.Entities.csproj" /> 
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EntitiesConfiguration\" />
  </ItemGroup>




</Project>
