<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />

    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Canaa.DataContracts\Canaa.DataContracts.csproj" />
    <ProjectReference Include="..\Canaa.FN.BusinessComponents\Canaa.FN.BusinessComponents.csproj" />
    <ProjectReference Include="..\Canaa.Infra.Entities\Canaa.Infra.Entities.csproj" />
    <ProjectReference Include="..\Canaa.Infra.ExternalServices\Canaa.Infra.ExternalServices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Midias\Postagem\" />
  </ItemGroup>

</Project>
