# Imagem apenas de runtime do .NET 9
FROM mcr.microsoft.com/dotnet/aspnet:9.0

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos já publicados para dentro da imagem
COPY . .

# Define o comando de entrada
ENTRYPOINT ["dotnet", "Canaa.dll"]
